### ISSUE TITLE
derived parameter p_cap_site throws error

### ISSUE THREAD

**Issue by nthaydt** [djhocking/co_canal_turtles#5]
Latest commit: ece2dceefe330ad14fbad3d83d553771fa10e7c1
Model runs with p_cap_site hashed out - found on line 120 in run_jags script.

If p_cap_site is not hashed out, running the model produces the following error:
Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: Error in node p_cap_site[11]
Invalid parent values

The index on p_cap_site which throws an error seems to vary depending on the model run (the error was thrown at p_cap_site[6] for the previous test attempt).

**Comment by djhocking** [comment]
`p_cap_site` became a problem for species at sites with zero captures because then there was a division by zero. With the augments, it was problematic to average over individuals (averaging in lots of zero probabilities. There is no if_else statement to handle that in JAGS and couldn't just average over individuals in the pop. Added code to calculated it with post-processing in R in the `mcmc_check.R` script.
